name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: docker-hub
    steps:
    - uses: actions/checkout@v4

    - uses: docker/login-action@v3.2.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - uses: docker/setup-buildx-action@v3.3.0

    - uses: docker/build-push-action@v5.3.0
      with:
        tags: micheal65536/vienna:eventbus-latest
        target: vienna-eventbus
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - uses: docker/build-push-action@v5.3.0
      with:
        tags: micheal65536/vienna:objectstore-latest
        target: vienna-objectstore
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - uses: docker/build-push-action@v5.3.0
      with:
        tags: micheal65536/vienna:apiserver-latest
        target: vienna-apiserver
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - uses: docker/build-push-action@v5.3.0
      with:
        tags: micheal65536/vienna:utils-locator-latest
        target: vienna-utils-locator
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - uses: docker/build-push-action@v5.3.0
      with:
        tags: micheal65536/vienna:utils-cdn-latest
        target: vienna-utils-cdn
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - uses: docker/build-push-action@v5.3.0
      with:
        tags: micheal65536/vienna:buildplate-launcher-latest
        target: vienna-buildplate-launcher
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - uses: docker/build-push-action@v5.3.0
      with:
        tags: micheal65536/vienna:tappablesgenerator-latest
        target: vienna-tappablesgenerator
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - uses: docker/build-push-action@v5.3.0
      with:
        tags: micheal65536/vienna:utils-tools-buildplate-importer-latest
        target: vienna-utils-tools-buildplate-importer
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
